This file is a QuantumComputer.py abreviated to qc5.py - I needed
I needed to do a lot of tweaking for it to work in Python 3.
I also added a '?' To inspect the qubits after an operation.

I am not sure of its correct functioning!
Depending on the sequence of commands, it has errors.
I am using the   teste1-qc5.py   to call   qc5.py  (QuantumComputer.py)

If you send:

y q [0];
cx q [3], q [0];

he says:
"File" C: \ Users \ User \ Dropbox \ QUBIT \ FONTES \ qc5.py ", line 432, in get_quantum_register_containing
     Raise ValueError ("qubit% s not found"% name)
ValueError: qubit not found

If you send:

bloch q [4];
h q [4];
cx q [3], q [0];

he says:
"File" C: \ Users \ User \ Dropbox \ QUBIT \ FONTES \ qc5.py ", line 363, in num_qubits
     If state.shape [1]! = 1 or num_qubits not in [1,2,3,4,5]:
IndexError: tuple index out of range

I do not know the logic rules of the quantum operators ... so it's being rather difficult to correct these problems.
I plan to validate QuantumCo